-- migrate:up

-- ---------------------------------------------------------------------------
-- A person's names as the people search compares them (checklist row perf-indexes)
--
-- The search folds case and accents on every row it reads, three expressions per
-- person, so a search scanned the church and recomputed every name each time:
-- about 60 ms at 10,000 people, against 2.4 ms for the same search over names
-- already folded (measured on dfc_perf, 2026-10-02).
--
-- Generated by the database from the names as entered, so nothing writes them and
-- no write path can leave them behind. The names themselves are untouched: section
-- 3 normalizes for comparison only and never alters the stored values, and these
-- are a derived copy beside them, as `mobile_number_normalized` is.
--
-- The two strings are ACCENTED and UNACCENTED in `src/people/people.shared.ts`,
-- character for character; `test/database/person-search-names.spec.ts` fails if
-- they part. Additive and with no effective date, so it backdates nothing.
-- ---------------------------------------------------------------------------

ALTER TABLE persons
  ADD COLUMN search_first_name text GENERATED ALWAYS AS (
    lower(translate(
      first_name,
      'áàâäãåéèêëíìîïóòôöõúùûüñçÁÀÂÄÃÅÉÈÊËÍÌÎÏÓÒÔÖÕÚÙÛÜÑÇ',
      'aaaaaaeeeeiiiiooooouuuuncAAAAAAEEEEIIIIOOOOOUUUUNC'
    ))
  ) STORED,
  ADD COLUMN search_last_name text GENERATED ALWAYS AS (
    lower(translate(
      last_name,
      'áàâäãåéèêëíìîïóòôöõúùûüñçÁÀÂÄÃÅÉÈÊËÍÌÎÏÓÒÔÖÕÚÙÛÜÑÇ',
      'aaaaaaeeeeiiiiooooouuuuncAAAAAAEEEEIIIIOOOOOUUUUNC'
    ))
  ) STORED,
  ADD COLUMN search_full_name text GENERATED ALWAYS AS (
    lower(translate(
      first_name || ' ' || last_name,
      'áàâäãåéèêëíìîïóòôöõúùûüñçÁÀÂÄÃÅÉÈÊËÍÌÎÏÓÒÔÖÕÚÙÛÜÑÇ',
      'aaaaaaeeeeiiiiooooouuuuncAAAAAAEEEEIIIIOOOOOUUUUNC'
    ))
  ) STORED;

-- migrate:down

-- Derived from the names and holding nothing else, so dropping them loses nothing.
ALTER TABLE persons
  DROP COLUMN search_full_name,
  DROP COLUMN search_last_name,
  DROP COLUMN search_first_name;
